### ISSUE TITLE
getOwnEnumPropSymbols.default error

### ISSUE THREAD

**Issue by DarkAiR** [yeoman/stringify-object#71]
In version 4.0.0 I get an error in the code:
`...getOwnEnumPropSymbols.default(input),`

`index.js?feff:94 Uncaught (in promise) TypeError: get_own_enumerable_property_symbols__WEBPACK_IMPORTED_MODULE_2___default.a.default is not a function or its return value is not iterable`

Code below works
`...getOwnEnumPropSymbols(input),`

**Comment by sindresorhus** [comment]
This is a problem with Webpack or your Webpack config. I suggest opening an issue on Webpack instead.

**Comment by changhuali** [comment]
I meet this problem too with rollup, so i don't think this is a problem with webpack!
`import getOwnEnumPropSymbols from 'get-own-enumerable-property-symbols'
let objectKeys = [
    ...Object.keys(input),
    ...getOwnEnumPropSymbols.default(input),
];
`
get-own-enumerable-property-symbols is a commonjs package, so here should be ...getOwnEnumPropSymbols(input)?

**Comment by changhuali** [comment]
> This is a problem with Webpack or your Webpack config. I suggest opening an issue on Webpack instead.

The value of the default export is `exports.default` if the CommonJS file has an `Object.defineProperty(exports, "__esModule", { value: true })`, otherwise it's `module.exports`, `__esModule` is true in `get-own-enumerable-property-symbols` package , so `...getOwnEnumPropSymbols.default(input)` here should be changed to `...getOwnEnumPropSymbols.default(input)`
